schema_version: 1

context:
  name: ogg
  version: 1.3.5

package:
  name: lib${{ name|lower }}
  version: ${{ version }}

source:
  url: http://downloads.xiph.org/releases/${{ name }}/lib${{ name }}-${{ version }}.tar.gz
  sha256: 0eb4b4b9420a0f51db142ba3f9c64b333f826532dc0f48c6410ae51f4799b664

build:
  number: 1

requirements:
  build:
    - ${{ stdlib("c") }}
    - ${{ compiler("c") }}
    - if: win
      then: cmake
    - if: unix
      then: gnuconfig
    - if: unix
      then: make
    - if: unix
      then: pkgconfig
  run_exports:
    - ${{ pin_subpackage('libogg', upper_bound='x.x') }}

tests:
  - script:
      - if: unix
        then: test ! -f $PREFIX/lib/libogg.a
      - if: unix
        then: test -f $PREFIX/lib/libogg${SHLIB_EXT}
      - if: unix
        then: test -f $PREFIX/include/ogg/ogg.h
      - if: unix
        then: test -f $PREFIX/include/ogg/config_types.h
      - if: unix
        then: test -f $PREFIX/include/ogg/os_types.h
      - if: win
        then: if not exist %LIBRARY_LIB%\\ogg.lib exit 1
      - if: win
        then: if not exist %LIBRARY_BIN%\\ogg.dll exit 1
      - if: win
        then: if not exist %LIBRARY_INC%\\ogg\\config_types.h exit 1
      - if: win
        then: if not exist %LIBRARY_INC%\\ogg\\ogg.h exit 1
      - if: win
        then: if not exist %LIBRARY_INC%\\ogg\\os_types.h exit 1

about:
  license: BSD-3-Clause
  license_file: COPYING
  summary: OGG media container
  description: |
    OGG media container. This is the native format and the recommended container
    for Xiph codecs.
  homepage: https://www.xiph.org/
  documentation: https://wiki.xiph.org/

extra:
  recipe-maintainers:
    - dschreij
    - wolfv
