appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {linux_aarch64: default, linux_ppc64le: default}
travis:
  secure: {BINSTAR_TOKEN: CPdKKac8o1sa44zq/c28vTcolpiI9/khl5Xq+0VaFze2q6D+yjqnSpJ6gezc578fDTTnzvzqqdcc+GU1mMhmrMA/1IyRk3VNaDiE0uCzkeH+KVSO9K/xidGxetAdu5XFk71RR3ZjJXsMgIJCv4fQjPopIzNrSOF8CbbxSx6IYgdKr5ShrnsEsxxPo9n08w2HlLHa+v+9JP1ZAWnMNCO6viZs0jcEmE+yp5Ng9vtLjJAbX4aNmPontYmZkwJetD4gQ7UpG5u3yFWHd+ZkP/5mbrd4Cv8ZsWat6E5D7+jTUDh41dgmCHinOhwFdmPUOVg/crD1nOBxp/teWamfxq2hp1ZD1uiX3Zwi+gqVME1SKieTiRxx/HBHDCfZhgZ2Dx9+ElsJJ9ndJP+MBCFfYjot18E4c4Pqno5o/looaK9qvKftVvjL2xIXnMUNoIpQAHIyAc3FWHWn6dH38xdGLD3zCT3uyjVbI84wuWJvoFT/Bk4dUD4mDvzrRNruMOMawjWXyPxfCgeu3r8jx7sn446SUnEJm1VZ9WJ2GSeT0MtZ+Xvs9MrBd+K5nZ7UxBo3yyFmzS5uUsrbtsJBEFUtRzF1MgbiURggAjKCq66RtFujrBvN4s5elqCwrI9PR3WyiDTafqDjYvEOy8XL0UeeBArsv3xif5CVwEKI2/M8oUASGRU=}
